const CUSTOMER_LIST_HEADING = [
    "Name",
    "Phone Number",
    "Address",
    "Current Date",
];

const CUSTOMER_LIST = [
    {
        uuid: "B5RXCDS6BC",
        full_name: "Far McTavish",
        email: "fmctavish0@chicagotribune.com",
        phone_number: "825-744-7788",
        address: "87249 American Terrace",
        city: "Isahaya",
        current_date: "25/10/2019",
    },
    {
        uuid: "8JASMGK9MUJ",
        full_name: "Reta Bras",
        email: "rbras1@upenn.edu",
        phone_number: "403-933-8527",
        address: "1003 Carey Street",
        city: "Jinniu",
        current_date: "08/01/2021",
    },
    {
        uuid: "7NG9MTNP7ZTZ",
        full_name: "Dot Gurys",
        email: "dgurys2@umn.edu",
        phone_number: "296-157-8526",
        address: "2172 Harbort Avenue",
        city: "Acheng",
        current_date: "02/07/2020",
    },
    {
        uuid: "15BGQGHD",
        full_name: "Teodoro Cowitz",
        email: "tcowitz3@tamu.edu",
        phone_number: "270-270-3352",
        address: "168 Forest Run Hill",
        city: "Yunga",
        current_date: "25/11/2020",
    },
    {
        uuid: "X7KYFJP",
        full_name: "Germain Parzis",
        email: "gparzis4@psu.edu",
        phone_number: "647-480-3003",
        address: "4 Springview Terrace",
        city: "Odivelas",
        current_date: "14/09/2019",
    },
    {
        uuid: "TBYDMSYYNPF",
        full_name: "Rona Jaffa",
        email: "rjaffa5@icio.us",
        phone_number: "740-733-7233",
        address: "98 Old Shore Place",
        city: "Kolodenka",
        current_date: "08/10/2020",
    },
    {
        uuid: "UOJCIMUNE",
        full_name: "Erasmus Bezzant",
        email: "ebezzant6@netvibes.com",
        phone_number: "892-630-7003",
        address: "7587 Blackbird Park",
        city: "Kuafeu",
        current_date: "19/04/2021",
    },
    {
        uuid: "8UPYCO2N",
        full_name: "Cash Barnicott",
        email: "cbarnicott7@google.pl",
        phone_number: "349-621-6733",
        address: "3 Blackbird Junction",
        city: "Sendung",
        current_date: "26/09/2019",
    },
    {
        uuid: "A3X8LLG",
        full_name: "Xaviera Klampk",
        email: "xklampk8@jimdo.com",
        phone_number: "245-164-1965",
        address: "699 Lakewood Gardens Avenue",
        city: "Injīl",
        current_date: "27/04/2021",
    },
];

export { CUSTOMER_LIST_HEADING, CUSTOMER_LIST };
