const ORDER_LIST = [
    {
        uuid: "1C3BC4EB7AN909363",
        total: 24282840,
        status: "unpaid",
        note: "",
        delivered_by: "Urban Fidele",
        created_at: "12/06/2021",
        created_by: "Leia Banane",
        export_from: "warehouse_2",
    },
    {
        uuid: "WBAKG7C57BE435914",
        total: 25734110,
        status: "paid",
        note: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        delivered_by: "Clarisse Boshere",
        created_at: "12/06/2021",
        created_by: "Kathie Easen",
        export_from: "warehouse_1",
    },
    {
        uuid: "WAUJT68E55A160257",
        total: 38865500,
        status: "paid",
        note: "Nulla tellus. In sagittis dui vel nisl.",
        delivered_by: "Clay Pesselt",
        created_at: "29/05/2021",
        created_by: "Cullie Willbond",
        export_from: "warehouse_2",
    },
    {
        uuid: "JN8AF5MRXFT907407",
        total: 51788430,
        status: "paid",
        note: "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.",
        delivered_by: "Hyacintha Camerana",
        created_at: "22/05/2021",
        created_by: "Gabey Hasley",
        export_from: "warehouse_2",
    },
    {
        uuid: "YV1672MK9D2362099",
        total: 64856260,
        status: "paid",
        note: "Curabitur gravida nisi at nibh.",
        delivered_by: "Udale Sporle",
        created_at: "15/05/2021",
        created_by: "Chauncey Waldren",
        export_from: "warehouse_1",
    },
];

export { ORDER_LIST };
