const PRODUCT_LIST_HEADING = ["Name", "Weight", "Use", "Protein", "Factory"];

const PRODUCT_LIST = [
    {
        uuid: "JTAARR",
        name: "Felis caracal",
        name_code: "feliscaracal",
        weight: 25,
        use: "bread",
        protein: 10.1,
        factory: "C Corp",
    },
    {
        uuid: "PZ0KDLYZEI",
        name: "Ceryle rudis",
        name_code: "cerylerudis",
        weight: 0.5,
        use: "noodle",
        protein: 11.1,
        factory: "A Corp",
    },
    {
        uuid: "YVJGKKUSR1",
        name: "Lycaon pictus",
        name_code: "lycaonpictus",
        weight: 25,
        use: "pizza",
        protein: 4.7,
        factory: "B Corp",
    },
    {
        uuid: "7PUFI331HN",
        name: "Felis concolor",
        name_code: "felisconcolor",
        weight: 25,
        use: "cake",
        protein: 2.3,
        factory: "A Corp",
    },
    {
        uuid: "MKAFAXR",
        name: "Thamnolaea cinnmomeiventris",
        name_code: "thamnolaeacinnmomeiventris",
        weight: 5,
        use: "other",
        protein: 2.3,
        factory: "A Corp",
    },
    {
        uuid: "KGRDZ6",
        name: "Diomedea irrorata",
        name_code: "diomedeairrorata",
        weight: 1,
        use: "bread",
        protein: 3.5,
        factory: "C Corp",
    },
    {
        uuid: "C7DJKSDDHC3",
        name: "Hippopotamus amphibius",
        name_code: "hippopotamusamphibius",
        weight: 5,
        use: "noodle",
        protein: 5.4,
        factory: "B Corp",
    },
    {
        uuid: "NX7FTCN2",
        name: "Papio cynocephalus",
        name_code: "papiocynocephalus",
        weight: 5,
        use: "pizza",
        protein: 1.6,
        factory: "C Corp",
    },
    {
        uuid: "MXCFEPYYPY9Q",
        name: "Eudyptula minor",
        name_code: "eudyptulaminor",
        weight: 5,
        use: "cake",
        protein: 5.2,
        factory: "C Corp",
    },
    {
        uuid: "ODPSSO8VDNU",
        name: "Phascogale calura",
        name_code: "phascogalecalura",
        weight: 40,
        use: "other",
        protein: 5.9,
        factory: "C Corp",
    },
    {
        uuid: "2QEMIG1S",
        name: "Ramphastos tucanus",
        name_code: "ramphastostucanus",
        weight: 40,
        use: "bread",
        protein: 8.3,
        factory: "A Corp",
    },
    {
        uuid: "Y1KAEIP",
        name: "Loxodonta africana",
        name_code: "loxodontaafricana",
        weight: 0.5,
        use: "noodle",
        protein: 7.6,
        factory: "C Corp",
    },
    {
        uuid: "FEM9ZHROSS",
        name: "Semnopithecus entellus",
        name_code: "semnopithecusentellus",
        weight: 1,
        use: "pizza",
        protein: 11.5,
        factory: "A Corp",
    },
    {
        uuid: "OUZZFP",
        name: "Crotalus triseriatus",
        name_code: "crotalustriseriatus",
        weight: 40,
        use: "cake",
        protein: 8.6,
        factory: "A Corp",
    },
    {
        uuid: "SNJTSA",
        name: "Colobus guerza",
        name_code: "colobusguerza",
        weight: 5,
        use: "other",
        protein: 2.6,
        factory: "A Corp",
    },
    {
        uuid: "O6HMYRP8",
        name: "Cynictis penicillata",
        name_code: "cynictispenicillata",
        weight: 5,
        use: "bread",
        protein: 2.1,
        factory: "C Corp",
    },
    {
        uuid: "LPCWIK8Q00K",
        name: "Tringa glareola",
        name_code: "tringaglareola",
        weight: 5,
        use: "noodle",
        protein: 11.2,
        factory: "B Corp",
    },
    {
        uuid: "XYAJIWVB",
        name: "Bassariscus astutus",
        name_code: "bassariscusastutus",
        weight: 1,
        use: "pizza",
        protein: 2.7,
        factory: "A Corp",
    },
    {
        uuid: "GJWU45J96",
        name: "Halcyon smyrnesis",
        name_code: "halcyonsmyrnesis",
        weight: 0.5,
        use: "cake",
        protein: 11.7,
        factory: "B Corp",
    },
    {
        uuid: "KA28IMQ1UMJ",
        name: "Picoides pubescens",
        name_code: "picoidespubescens",
        weight: 1,
        use: "other",
        protein: 1.1,
        factory: "C Corp",
    },
];

export { PRODUCT_LIST, PRODUCT_LIST_HEADING };
